### ISSUE TITLE
Project  Structure

### ISSUE THREAD

**Issue by ElectronicsArchiver** [OmerFlame/AltRant#2]
A basic but effective cleanup of the structure I would recommend
doing is to use a simple `Source` folder for most of the files
found in the root of the project.

Basically only the `README.md`, `LICENSE` and `.gitignore` should stay in root.

*Not sure about the Gemfile(s) in this configuration*

This would obviously greatly unclutter the project
and not push the README down as it now does.

**Comment by OmerFlame** [comment]
Because of the sheer mass of this project, I am too scared of changing the project structure. I agree that this should've been done a long time ago but I my biggest fear is that this project will fall into a massive misconfiguration that I will not know how to get out of.

**Comment by ElectronicsArchiver** [comment]
@OmerFlame Well you could simply make a branch with this 
change and test it with your IDE, that way your current 
project configuration wouldn't be affected~
